version: "3"
services:
  lucky-app:
    image: lucky-app:1.0
    ports:
      - 3500:3500
    restart: always
    env_file: docker.env
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  task-app:
    image: task-app:1.0
    ports:
      - 5000:5000
    restart: always
    env_file: docker.env
volumes:
  mongo-data:
