version: "3"
services:
  server-app:
    image: server-app:1.0
    ports:
      - 5001:5001
    restart: always
    env_file: docker.env
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  client-app:
    image: client-app:1.0
    ports:
      - 8000:8000
    restart: always
    env_file: docker.env
volumes:
  mongo-data:
